---
title: "changes_sjl"
author: "S J Lax"
date: "5 May 2016"
output: html_document
---

# Steph does unit testing! {.tabset}

## Setup

```{r setup, echo=FALSE, message = FALSE, warning=FALSE}
library(devtools)
devtools::load_all()

library(dplyr)
library(abind)
library(rms)
library(survival)
library(knitr)
library(tidyr)
library(ggplot2)
library(dplyr)
```

```{r data}
load("H:/Repos/prevR/data/prevsim.rda")
registry_data <- prevsim

summary(registry_data)
```

Using Stuart's custom function:

```{r test}
test_output <- function(old_func, new_func) {
    expected <- old_func()
    actual <- new_func()
    test <- tryCatch(all(expected == actual),
                     error=function(cond) FALSE)
    if (test) {
        message("Success!")
    } else {
        message("Failure...")
        message("Expected:")
        print(expected)
        message("Actual:") 
        print(actual)
    }
}
```

## counted_prevalence

```{r counted_prevalence}
countprev_dev <- function() {
  counted_prevalence(registry_data$entrydate, 
                     registry_data$eventdate, 
                     registry_data$status, 
                     start="2004-01-30", 9)
}
```

```{r counted_prevalence_current}
registry_years <- c("2003-01-30", "2004-01-30", "2005-01-30", "2006-01-30", "2007-01-30", "2008-01-30",
                      "2009-01-30", "2010-01-30", "2011-01-30", "2012-01-30", "2013-01-30")
registry_start_year <- 2
registry_end_year <- 10

registry_data$status2 <- ifelse(registry_data$eventdate > "2013-01-30", 0, registry_data$status)
registry_data$indicator_censored_at_index <- registry_data$status2
registry_data$date_initial <- registry_data$entrydate
registry_data$date_event <- registry_data$eventdate
registry_data$indicator <- registry_data$status
registry_data$survival_time <- registry_data$time
registry_data$age_initial <- registry_data$age
  
countprev_current_output <- function() {
  
  counted_prevalence_current(registry_data, registry_years, 
                             registry_start_year, registry_end_year)
}
```

```{r counted_prevalence_comp, message=T}
test_output(countprev_current_output, countprev_dev)
```

## prev_chisq

```{r check_prevalence}
prevalence_total <- prevalence(Surv(time, status) ~ sex(sex) + age(age) + entry(entrydate),
                               registry_data, N_years = 10, cure_time = 10*365, 
                               start='2004-01-30', num_years=9)

by_year_total <- prevalence_total[[1]]

prevchisq_dev <- function() {
  prev_chisq(registry_data$entrydate,
            registry_data$eventdate, 
            registry_data$status, 
            start="2004-01-30", 9,
            by_year = by_year_total)
}
```

```{r check_prevalence_current}
prevchisq_current_output <- function() {
  prev_chisq_current(registry_data, registry_years, registry_start_year, registry_end_year, by_year = by_year_total)
}
```

```{r check_prevalence_comp, message=T}
test_output(prevchisq_current_output, prevchisq_dev)
```

## incidence_age_distribution

```{r check_incidence_age_distribution}
registry_data_r <- registry_data[registry_data$entrydate >= "2004-01-30",]

incidence_age_distribution_dev <- function() {
  incidence_age_distribution(registry_data_r$age)
}
```

```{r check_incidence_age_distribution_current}
incidence_age_distribution_current_output <- function() {
  incidence_age_distribution_current(registry_data, registry_years, registry_start_year, registry_end_year)
}
```

```{r check_incidence_age_distribution_comp, message=T}
test_output(incidence_age_distribution_current_output, incidence_age_distribution_dev)
```

## functional_form_age

```{r check_functional_form_age}
functional_form_age_dev <- function() {
  functional_form_age(registry_data_r)
}
```

```{r check_functional_form_age_current}
functional_form_age_current_output <- function() {
  functional_form_age_current(registry_data, registry_years, registry_start_year, registry_end_year)
}
```

```{r check_functional_form_age_comp, message=T}
test_output(functional_form_age_current_output, functional_form_age_dev)
```