#' Estimates consistency of incidence data with an homogeneous Poisson process.
#'
#' This function compares the actual variance of the yearly incidence rates with rates
#' simulated from a Poisson process with overall rate equal to the overall mean rate.
#'
#' @param data Vector of absolute incidence values for each included year of the registry
#' as generated by \code{incidence}.
#' @param N_sim Integer to specify number of simulations to perform.
#' @return Vector of p-values for over- and under-dispersion based on the position of the
#' observed sequence variance in the distribution.
#' @examples
#' data(prevsim)
#'
#' inc <- incidence(prevsim$entrydate)
#' test_poisson_fit(inc)
#' @export test_poisson_fit
test_poisson_fit <- function(data, N_sim = 100000) {
    var_sim <- vapply(seq(N_sim), function(i) var(rpois(length(data), mean(data))), numeric(1))
    c(length(var_sim[var_sim > var(data)])/N_sim, length(var_sim[var_sim <= var(data)])/N_sim)
}

#' Plots the age distribution of incident cases in the registry data.
#'
#' @param agedata Vector of ages at diagnosis for each patient in the registry.
#' @param df Degrees of freedom for the smooth.
#' @return Plot of the raw data and smoothed age distribution function.
#' @examples
#' data(prevsim)
#'
#' incidence_age_distribution(prevsim$age)
#' @export incidence_age_distribution
incidence_age_distribution <- function(agedata, df=10) {

    ages <- vapply(seq(100), function(i) sum(floor(agedata) + 1 == i), numeric(1))

    plot(0:99, ages[1:100], pch=20, xlab="age (years)", ylab="incident cases")
    smage <- smooth.spline(0:99, ages[1:100], df=df)
    lines(smage, col="blue", lwd=2)

}

#' Inspect functional form of age.
#'
#' @param form Formula where the LHS is represented by a standard \code{Surv} object, and the RHS
#' has the function argument \code{age} to specify the column containing age data.
#'
#' This formula is used in the following way:
#'
#' \code{Surv(time, status) ~ age(age_column_name)}
#' @param data A data frame with the corresponding column names provided in \code{form}.
#' @param df The desired degrees of freedom for the smooth.
#' @return Plots and model summary relating to the functional form of age.
#' @examples
#' data(prevsim)
#'
#' functional_form_age(Surv(time, status) ~ age(age), prevsim)
#' @export functional_form_age
#' @importFrom rms datadist
#' @importFrom rms cph
#' @importFrom rms rcs
#' @importFrom survival coxph
functional_form_age <- function(form, data, df=4) {

    ### TO DO/discuss:
    # ?No reason why this can't be applied to any continuous covariate, just need to change age() and age_ prefixes
    # ?How to neaten up the output; control side effects, do we need both plots etc
    # ?Too much duplication of code here with prevalence()
    ###

    # Extract required column names from formula
    terms <- terms(form, 'age')
    special_indices <- attr(terms, 'specials')

    if (any(sapply(special_indices, is.null)))
        stop("Error: provide function term for age.")

    v <- as.list(attr(terms, 'variables'))[-1]
    var_names <- unlist(lapply(special_indices, function(i) v[i]))
    age_var <- .extract_var_name(var_names$age)

    # Extract survival formula
    response_index <- attr(terms, 'response')
    resp <- v[response_index][[1]]

    psp_surv_form <- as.formula(paste(deparse(resp), '~ pspline(',
                                      age_var, ', ', df, ')', sep=''))

    cxnl <- survival::coxph(psp_surv_form, data)
    output1 <- summary(cxnl)

    plt1 <- termplot(cxnl)

    f <<- rms::datadist(data)
    options(datadist="f")

    rcs_surv_form <- as.formula(paste(deparse(resp), '~ rcs(',
                                      age_var, ', ', df, ')', sep=''))

    mod_rms <- rms::cph(rcs_surv_form, data, x=TRUE, y=TRUE, surv=T, time.inc=1)
    output2 <- anova(mod_rms)
    output3 <- summary(mod_rms)

    plt2 <- plot(eval(parse(text=paste('Predict(mod_rms, ', age_var,')', sep = ''))), lwd=3, adj.subtitle=T)

    list(plt1, plt2, output1, output2, output3)
}

#' ?
#'
#' @param age Age of example patient.
#' @param sex Sex of example patient ("Male" or "Female").
#' @param wb Weibull model fitted to the data.
#' @return ?
dfr_sc <- function(age, sex, wb) {
    if (sex == "Male") {
        sexn <- 0
    } else {
        sexn <- 1
    }
    return(exp(wb$coef[1] + age*wb$coef[2] + sexn*wb$coef[3]))
}

#' ?
#'
#' @param t ?
#' @param shape ?
#' @param scale ?
#' @return ?
wb_Su <- function(t, shape, scale) {
    return(exp(-(t/scale)^shape))
}

#' ?
#'
#' @param t ?
#' @param shape ?
#' @param scale ?
#' @return ?
wb_haz <- function(t, shape, scale) {
    return((shape/scale)*(t/scale)^(shape-1))
}

#' ?
#'
#' @param age Age of example patient.
#' @param sex Sex of example patient ("Male" or "Female").
#' @param the_length Number of days to predict.
#' @param wb Weibull model fitted to the data.
#' @return ?
plot_haz <- function(age, sex, the_length=3000, wb) {
    s_time <- seq(0, the_length, by=1)
    haz <- wb_haz(s_time, dfr_sh, dfr_sc(age, sex, wb))
    plot(s_time, haz, type="l", lwd=2, col="red", ylim=c(0,0.002),
         main=paste("age = ", age, ", sex =", sex), xlab="survival (days)", ylab="probability")
}

#' ?
#'
#' @param data Population survival dataset.
#' @param age Age of example patient.
#' @param sex Sex of example patient ("Male" or "Female").
#' @param the_length Number of days to predict.
#' @return ?
plot_population_hazard <- function(data, age, sex, the_length=3000) {
    if(sex == "Male") sex = "Males"
    if(sex == "Female") sex = "Females"
    daily_survival_rate <- function(data, sex)
        lines(0:(the_length-1), daily_survival_rate[(365*age):(365*age + the_length - 1)],
              col="blue", lwd=2)
}

#' ?
#'
#' @param age Age of example patient.
#' @param sex Sex of example patient ("Male" or "Female").
#' @param the_length Number of days to predict.
#' @param wb Weibull model fitted to the data.
#' @return ?
plot_Su <- function(age, sex, the_length=3000, wb) {
    s_time <- seq(0, the_length, by=1)
    Su <- wb_Su(s_time, dfr_sh, dfr_sc(age, sex, wb))
    plot(s_time, Su, type="l", lwd=2, col="red", ylim=c(0,1),
         main=paste("age = ", age, ", sex =", sex), xlab="survival (days)", ylab="probability")
}

#' ?
#'
#' @param data Population survival dataset.
#' @param age Age of example patient.
#' @param sex Sex of example patient ("Male" or "Female").
#' @param the_length Number of days to predict.
#' @return ?
plot_pop_Su <- function(data, age, sex, the_length=3000) {
    if(sex == "Male") sex = "Males"
    if(sex == "Female") sex = "Females"
    daily_survival_rate <- function(data, sex)
        lines(1:the_length, cumprod(1 - daily_survival_rate[(age*365):(age*365 + the_length - 1)]),
              col="cyan", lwd=2)
}

#' ?
#'
#' @param data A registry dataset of patient cases generated using load_data().
#' @param registry_years A vector of dates delineating years of the registry.
#' @param registry_start_year Ordinal defining the first year of the registry data to be used.
#' @param age Age of example patient.
#' @param sex Sex of example patient ("Male" or "Female").
#' @param limits ?
#' @param colour ?
#' @return ?
plot_km <- function(data, registry_years, registry_start_year, age,
                    sex, limits, colour="green") {
    if (sex == "Male") {
        sexn <- 0
    } else {
        sexn <- 1
    }
    dfr_r <- data[data$date_initial >= registry_years[registry_start_year],]
    kma <- survfit(Surv(survival_time, indicator) ~ 1,
                   data=dfr_r[dfr_r$sex == sexn & dfr_r$age_initial > age-limits &
                                  dfr_r$age_initial < age + limits, ])
    lines(kma, lwd=1, col=colour, conf.int=T)
}

#' Inspect bootstrapped survival curves for an example patient with a given age and sex.
#'
#' @param form Formula where the LHS is represented by a standard \code{Surv} object, and the RHS has three special function arguments:
#' \code{age}, the column where age is located;
#' \code{sex}, the column where sex is located; and
#' \code{entry}, the column where dates of entry to the registry are located.
#'
#' This formula is used in the following way:
#'
#' \code{Surv(time, status) ~ age(age_column_name) + sex(sex_column_name) + entry(entry_column_name)}
#'
#' Using the supplied \code{prevsim} dataset, it is therefore called with:
#'
#' \code{Surv(time, status) ~ age(age) + sex(sex) + entry(entrydate)}
#' @param data A data frame with the corresponding column names provided in \code{form}.
#' @param start Date from which incident cases are included, in the format YYYY-MM-DD. Defaults to the earliest incident case in
#' the supplied registry.
#' @param age Age of example patient.
#' @param sex Sex of example patient.
#' @param N_boot Number of replicates.
#' @return Generates a plot of survival curves fitted to each bootstrapped sample (grey) with the survival curve plotted
#' to the raw data overlaid (orange).
#' @examples
#' data(prevsim)
#'
#' boot_eg(form = Surv(time, status) ~ age(age) + sex(sex) + entry(entrydate),
#'                     data = prevsim,
#'                     start = "2004-01-30",
#'                     age = 65,
#'                     sex = "Male")
boot_eg <- function(form, data, age, sex, start=NULL, N_boot = 1000) {

    spec <- c('age', 'sex', 'entry')
    terms <- terms(form, spec)
    special_indices <- attr(terms, 'specials')

    if (any(sapply(special_indices, is.null)))
        stop("Error: provide function terms for age, sex, and entry date.")

    v <- as.list(attr(terms, 'variables'))[-1]
    var_names <- unlist(lapply(special_indices, function(i) v[i]))

    age_var <- .extract_var_name(var_names$age)
    sex_var <- .extract_var_name(var_names$sex)
    entry_var <- .extract_var_name(var_names$entry)

    # Extract survival formula
    response_index <- attr(terms, 'response')
    resp <- v[response_index][[1]]
    non_covariate_inds <- c(response_index, unlist(special_indices))
    covar_names <- as.list(attr(terms, 'variables'))[-1][-non_covariate_inds]  # First -1 to remove 'list' entry

    if (length(covar_names) > 0)
        stop("Error: functionality isn't currently provided for additional covariates.")

    data[, sex_var] <- as.factor(data[, sex_var])
    if (length(levels(data[, sex_var])) > 2)
        stop("Error: function can't currently function with more than two levels of sex.")

    # Determine the registry years of interest from assessing the code
    if (is.null(start))
        start <- min(data[, entry_var])

    req_covariate <- ifelse(length(levels(data[, sex_var])) == 1, age_var, paste(age_var, sex_var, sep='+'))
    surv_form <- as.formula(paste(deparse(resp), '~',
                                  req_covariate,
                                  paste(covar_names, collapse='+')))

    data_r = data[data[, entry_var] >= start, ]
    wb_boot <- .registry_survival_bootstrapped(surv_form, data_r)

    wb_lines <- matrix(0, nrow=N_boot, ncol=5000)
    n <- seq(5000)

    if (sex == "Male") {
        wb_lines <- sapply(seq(N_boot),
                           function(i) 1 - pweibull(n, scale=exp(wb_boot[i, 1] + age*wb_boot[i, 2]), shape=1/wb_boot[i, 4]))
    } else {
        wb_lines <- sapply(seq(N_boot),
                           function(i) 1 - pweibull(n, scale=exp(wb_boot[i, 1] + age*wb_boot[i, 2] +
                                                                     wb_boot[i, 3]), shape=1/wb_boot[i, 4]))
    }

    plot(NA, xlim=c(1,5000), ylim=c(0,1), main = paste("age = ", age, ", sex = ", sex))
    sapply(seq(N_boot),
           function(i) lines(wb_lines[, i], lwd=1, col="grey"))

    wb <- survreg(surv_form, data_r)

    if (sex == "Male") {
        A <- 1 - pweibull(n, scale=exp(wb$coef[1] + age*wb$coef[2]), shape=1/wb$scale)
        lines(A, col="orange", lwd=3, lty=3)
    } else {
        A <- 1 - pweibull(n, scale=exp(wb$coef[1] + age*wb$coef[2] + wb$coef[3]), shape=1/wb$scale)
        lines(A, col="orange", lwd=3, lty=3)
    }

}

plot.survfit.prev <- function(object, pct_show=0.5) {
    library(ggplot2)
    library(tidyr)
    library(dplyr)

    num_boot <- dim(object$surv)[1]
    num_days <- dim(object$surv)[2]
    if (num_days != length(object$time))
        stop("Error: Number of survival probabilities not consistent with time variable.")

    df <- data.frame(object$surv)
    colnames(df) <- seq(num_days)
    df$bootstrap <- seq(num_boot)

    gathered <- gather(df, time, survprob, -bootstrap)

    smooth <- gathered %>%
        group_by(time) %>%
        summarise(mx=quantile(survprob, 0.975),
                  mn=quantile(survprob, 0.025)) %>%
        arrange(as.numeric(time))

    row_inds <- apply(df[, -ncol(df)], 1, function(x) mean(x > smooth$mx | x < smooth$mn) > pct_show)

    outliers <- df[row_inds, ] %>%
                    gather(time, survprob, -bootstrap)

    ggplot() +
        geom_line(data=outliers, aes(x=as.numeric(time), y=survprob, group=as.factor(bootstrap))) +
        geom_line(data=data.frame(time=seq(num_days), survprob=object$fullsurv),
                  aes(x=as.numeric(time), y=survprob), colour='orange') +
        geom_ribbon(data=smooth, aes(x=as.numeric(time), ymin=mn, ymax=mx), alpha=0.3) +
        theme_bw()
}
#' Chi squared test between prevalence prediction and observed values in the registry.
#'
#' @param object A \code{prevalence} object.
#' @return P-value from a chi-squared test of difference between prevalence prediction and counted prevalence at the index date.
#' @examples
#' data(prevsim)
#'
#' obj <- prevalence(Surv(time, status) ~ age(age) + sex(sex) + entry(entrydate) + event(eventdate),
#'                   data=prevsim, num_years_to_estimate = c(5, 10), population_size=1e6,
#'                   start = "2005-09-01",
#'                   num_reg_years = 8, cure = 5)
#'
#' test_prevalence_fit(obj)
#' @export test_prevalence_fit
test_prevalence_fit <- function(object) {
    observed <- object$counted
    predicted <- rev(object$simulated$mean_yearly_contributions[1:object$nregyears])
    chi <- sum(((observed - predicted)^2)/predicted)
    1 - pchisq(chi, object$nregyears - 1)
}