#' Count prevalence from registry data.
#'
#' @param entry Vector of diagnosis dates for each patient in the registry.
#' @param events Vector of dates corresponding to the indicator variable.
#' @param status Vector of binary values indicating if an event has occurred for each patient in the registry.
#' @param start Date from which incident cases are included.
#' @param num_reg_years Integer representing the number of complete years of the registry for which incidence is to be calculated.
#' @param indexdate Index date at which to estimate prevalence.
#' #' @return A count of prevalence at the index date subdivided by year of diagnosis and inclusion in the registry.
#' @examples
#' counted_prevalence(registry_data$entrydate,
#'                    registry_data$eventdate,
#'                    registry_data$status,
#'                    indexdate = "2013-01-30",
#'                    start="2004-01-30", num_reg_years=8)
counted_prevalence <- function(entry, eventdate, status, start=NULL, num_reg_years=NULL, indexdate=NULL) {

    if (is.null(start))
        start <- min(entry)

    if (is.null(num_reg_years))
        num_reg_years <- floor(as.numeric(difftime(max(entry), start) / 365.25))

    registry_years <- .determine_registry_years(start, num_reg_years)

    if (is.null(indexdate))
        indexdate <- registry_years[length(registry_years)]

    # Need no NAs for this!
    clean <- complete.cases(entry) & complete.cases(eventdate) & complete.cases(status)
    entry <- entry[clean]
    eventdate <- eventdate[clean]
    status <- status[clean]

    status_at_index <- ifelse(eventdate > indexdate, 0, status)

    per_year <- incidence(entry, start, num_reg_years=num_reg_years)
    num_cens <- vapply(seq(num_reg_years), function(i)
                            sum(status_at_index[entry >= registry_years[i] & entry < registry_years[i + 1]]),
                       numeric(1))
    per_year - num_cens
}


#' Predict prevalence for a given number of years.
#'
#' @param form ...
#' @param data Dataset of patient cases generated by load_data().
#' @param num_years_to_estimate Integer representing number of years to model.
#' @param cure Integer defining cure model assumption for the calculation (in years).
#' @param start Date from which incident cases are included.
#' @param num_reg_years Integer representing the number of complete years of the registry for which incidence is to be calculated.
#' @param N_boot Integer for number of bootstrapped calculations to perform.
#' @param max_yearly_incidence Integer larger than the expected yearly incidence
#'        to allow for variation in incidence between years.
#' @param pop_vers ...
#' @param colnames Vector of column names indicating required variables: age, sex, entry, status and time.
#' @return Predicted number of prevalent cases for each year, the age distribution of the
#'        prevalent cases, an indication of sampling variation and raw incidence data to
#'        allow for crosschecking with previous calculations.
#' @examples
<<<<<<< HEAD
#' prevalence_total <- prevalence(Surv(time, status) ~ sex(sex) + age(age) + entry(entrydate),
#' registry_data, num_years_to_estimate, cure, start='2004-01-30', num_reg_years=9)
prevalence <- function(form, data, num_years_to_estimate,
                       cure=NULL, start=NULL, num_reg_years=NULL,
                       N_boot=1000, max_yearly_incidence=500,
                       population_data=NULL, n_cores=1) {

    ############################################
    #
    # TODO Remove when finished debugging
    #set.seed(17)
    #num_years_to_estimate = 10
    ##data = subset(registry_data, sex==0)
    #data = registry_data
    #num_years_to_estimate = num_years_to_estimate
    #cure_days = cure*365
    #start = '2005-09-01'
    #num_reg_years = 8
    #N_boot = 1000
    #max_yearly_incidence = 500
    #form = Surv(stime, status) ~ age(age) + sex(sex) + entry(DateOfDiag)
    #population_data = NULL
    #parallel = F
    ############################################
    #prelim <- read.csv("R:/HMRN/Substudies/Prevalence/20140402_Prevalence_All/NLPHL/20140414_NLPHL_all.csv", header=T)
    #prelim$DateOfDiag <- as.Date(prelim$DateOfDiag, format="%d/%m/%Y")
    #prelim$EventDate <- as.Date(prelim$EventDate, format="%d/%m/%Y")
    #prelim$stime <- as.double(difftime(prelim$EventDate, prelim$DateOfDiag, units="days"))
    #prelim$stime <- ifelse(prelim$stime <= 0, 1, prelim$stime)
    #prelim <- prelim[!is.na(prelim$sex), ]
    #prelim_r <- prelim[prelim$DateOfDiag >= "2006-09-01", ]
    #
    #registry_years = sapply(7:15, function(x) sprintf("20%02d-09-01", x))
    #form = Surv(stime, status) ~ sex(sex) + age(age) + entry(DateOfDiag)
    #start='2007-09-01'
    #
    #num_reg_years=8
    #num_years_to_estimate <- 10
    #cure <- 3
    #cure_days = cure * 365
    #N_boot = 1000
    #pop_vers = 1
    #max_yearly_incidence = 500
    #data = prelim_r
    #n_cores = 1
    #population_data = NULL
    #############################################

=======
#' names = list(age = 'age', sex = 'sex', entry_date = 'DateOfDiag', status = 'status', time ='stime')
#' prevalence_total <- prevalence(registry_data,
#'                                N_years = 10,
#'                                cure_time = 10*365,
#'                                start = "2005-09-01",
#'                                num_reg_years = 8,
#'                                colnames = names)
#'
prevalence <- function(form, data, N_years,
                       cure_time=NULL, start=NULL, num_reg_years=NULL,
                       N_boot=1000, max_yearly_incidence=500,
                       population_data=NULL, n_cores=1) {

>>>>>>> 8ee5417fd88bc48262d9b98deff8da3c8bddf276
    if (n_cores > 1) {
        if (!require(doParallel)) {
            warning("doParallel not installed. Running program serially instead.")
            n_cores <- 1
        }
    }

    # Extract required column names from formula
    spec <- c('age', 'sex', 'entry')
    terms <- terms(form, spec)
    special_indices <- attr(terms, 'specials')

    if (any(sapply(special_indices, is.null)))
        stop("Error: Provide function terms for age, sex, and entry date.")

    v <- as.list(attr(terms, 'variables'))[-1]
    var_names <- unlist(lapply(special_indices, function(i) v[i]))

    age_var <- .extract_var_name(var_names$age)
    sex_var <- .extract_var_name(var_names$sex)
    entry_var <- .extract_var_name(var_names$entry)

    # Extract survival formula
    response_index <- attr(terms, 'response')
    resp <- v[response_index][[1]]
    non_covariate_inds <- c(response_index, unlist(special_indices))
    covar_names <- as.list(attr(terms, 'variables'))[-1][-non_covariate_inds]  # First -1 to remove 'list' entry

    if (length(covar_names) > 0)
        stop("Error: Functionality isn't currently provided for additional covariates.")

    # Assign cure if not provided, set to be so large that it has no impact
    ifelse(is.null(cure),
        cure_days <- (num_years_to_estimate + 1) * 365,
        cure_days <- cure * 365
    )

    data[, sex_var] <- as.factor(data[, sex_var])
    if (length(levels(data[, sex_var])) > 2)
        stop("Error: function can't currently function with more than two levels of sex.")

    # Determine the registry years of interest from assessing the code
    if (is.null(start))
        start <- min(data[, entry_var])

    if (is.null(num_reg_years))
        num_reg_years <- floor(as.numeric(difftime(max(data[, entry_var]), start) / 365.25))

    # Calculate population survival rates for each sex in dataset
    if (is.null(population_data)) {
        data(UKmortality)
        population_data <- UKmortality
    } else {
        # Obtain population data, and ensure it has the correct columns
        req_pop_names <- c('rate', 'age', 'sex')
        if (!all(sapply(req_pop_names, function(x) x %in% names(population_data)))) {
           stop("Error: The supplied population data frame must contain columns 'rate', 'age', 'sex'.")
        }
    }

    if (num_reg_years > num_years_to_estimate) {
        msg = paste("More registry years provided than prevalence is predicted for. Prevalence will be predicted for", num_years_to_estimate, "years using survival models built on", num_reg_years, "years of data.")
        message(msg)
    }

    population_data$sex <- as.factor(population_data$sex)

    if (!all(levels(data[, sex_var]) %in% levels(population_data$sex)))
        stop("Error: The same levels must be present in both the population and registry data. '0' and '1' by default where male is 0.")

    surv_functions <- lapply(setNames(levels(data[, sex_var]), levels(data[, sex_var])),
                             function(x) population_survival_rate(rate ~ age, data=subset(population_data, sex==x)))

    # Calculate bootstrapped weibull coefficients for registry data
    data_r <- data[data[, entry_var] >= start, ]

    # Specify whether to include sex as a survival variable or not, this should be included within the formula!
    req_covariate <- ifelse(length(levels(data_r[, sex_var])) == 1, age_var, paste(age_var, sex_var, sep='+'))
    surv_form <- as.formula(paste(deparse(resp), '~',
                                  req_covariate,
                                  paste(covar_names, collapse='+')))
    wb_boot <- registry_survival_bootstrapped(surv_form, data_r, N_boot, n_cores=n_cores)
    wb_boot <- wb_boot[sample(nrow(wb_boot)), ]

    # Run the prevalence estimator for each subgroup
    results <- lapply(levels(data_r[, sex_var]), function(x) {
        sub_data <- data_r[data_r[sex_var]==x, ]
        .prevalence_subgroup(sub_data[, age_var], sub_data[, entry_var], start, wb_boot, num_reg_years,
                             surv_functions[[x]], cure_days, as.numeric(x), max_yearly_incidence, num_years_to_estimate,
                             include_sex=length(levels(data_r[, sex_var])) == 2)
    })

    # Combine results if have more than 1 sex subgroup
    if (length(results) > 1) {
        # This is ugly but will work provided there aren't more than 2 sexs specified for, which is guarded
        # against anyway
        by_year_samples <- results[[1]]$cases + results[[2]]$cases
        post_age_dist <- abind(results[[1]]$post, results[[2]]$post, along=1)
        fix_rate <- rev(results[[1]]$fix + results[[2]]$fix)
    } else {
        by_year_samples <- results[[1]]$cases
        post_age_dist <- results[[1]]$post
        fix_rate <- results[[1]]$fix
    }
    by_year_avg <- rowMeans(by_year_samples)

    prev_out <- list(simulated_cases=by_year_avg, post_covar=post_age_dist, samples=by_year_samples, known_inc_rate=fix_rate,
                     popsurv=surv_functions, nyears=num_years_to_estimate, nregyears=num_reg_years, nbootstraps=N_boot)
    attr(prev_out, 'class') <- 'prevalence'
    prev_out
}


.prevalence_subgroup <- function(prior_age_d, entry, start, wboot, nregyears, survfunc,
                                 cure, sex, max_year_inc, nprevyears, include_sex) {
    fix_rate_rev <- rev(incidence(entry, start, num_reg_years=nregyears))
    mean_rate <- mean(fix_rate_rev)

    #  This is the new implementation of calculating the yearly predicted prevalence
    yearly_rates = lapply(1:nprevyears, .yearly_prevalence, wboot, mean_rate, nregyears, fix_rate_rev,
                          prior_age_d, survfunc, cure, sex, max_year_inc, include_sex)
    # Unflatten by_year samples
    by_year_samples = do.call(rbind, lapply(yearly_rates, function(x) x$cases))
    post_age_dist = abind(lapply(yearly_rates, function(x) x$post), along=3)
    return(list(cases=by_year_samples, post=post_age_dist, fix=fix_rate_rev))
}


.yearly_prevalence <- function(year, bootwb, meanrate, nregyears, fixrate, prior, dailysurv, cure, sex, max_inc, include_sex) {
    # Run the bootstrapping to obtain posterior distributions and # cases for this year
    post_results = apply(bootwb, 1, .post_age_bs, meanrate, nregyears, year-1, fixrate[year], prior, dailysurv,
                         cure, sex, max_inc, inreg=year<=nregyears, include_sex=include_sex)

    # Post_age_bs returns a list with 'cases' and 'post' values for the number of cases and posterior age distribution
    # Need to flatten this into single array for boot_out and 2D array for post_age_dist
    bs_cases <- vapply(post_results, function(x) x$cases, integer(1))
    bs_post <- do.call(rbind, lapply(post_results, function(x) x$post))
    return(list(cases=bs_cases, post=bs_post))
}


.post_age_bs <- function(coefs_bs, meanrate, nregyears, year, fixrate, prior, daily_surv, curetime,
                         sex, maxyearinc, inreg=TRUE, include_sex=TRUE) {
    post_age_dist <- rep(NA, maxyearinc)
    if (inreg){
        rate <- fixrate
    } else{
        rate <- max(0, rnorm(1, meanrate, sqrt(meanrate) / nregyears))
    }

    num_diag <- rpois(1, rate)

    if (num_diag > 0) {
        boot_age_dist <- sample(prior, num_diag, replace=T)
        time_since_diag <- year * 365 + runif(num_diag, 0, 365)

        # Combine data into a matrix
        bootstrapped_data <- matrix(c(rep(1, num_diag), boot_age_dist), nrow=num_diag)
        if (include_sex) {
            bootstrapped_data <- cbind(bootstrapped_data, rep(sex, num_diag))
        }

        is_dead <- as.logical(rbinom(num_diag, 1,
                                      1 - prob_alive(time_since_diag, bootstrapped_data,
                                                     curetime, boot_coefs=coefs_bs,
                                                     pop_surv_rate=daily_surv)))
        num_alive <- sum(!is_dead)
    } else {
        num_alive <- as.integer(0)
    }

    if (num_alive > 0)
        post_age_dist[1:num_alive] <- time_since_diag[!is_dead]/365 + boot_age_dist[!is_dead]

    return(list(cases=num_alive, post=post_age_dist))
}

<<<<<<< HEAD
#' Predict prevalence for a given number of years.
#'
#' @param data A registry dataset of patient cases generated using load_data().
#' @param registry_years A vector of dates delineating years of the registry.
#' @param registry_start_year Ordinal defining the first year of the registry data to be used.
#' @param registry_end_year Ordinal defining the last year of the registry data to be used.
#' @param daily_survival_males Population survival function (Males).
#' @param daily_survival_females Population survival function (Females).
#' @param cure Cure model assumption for the calculation (in years).
#' @param age_division Can be "None", "Adult" or "Paediatric".
#' @param age_cut A number, in years, to specify the cut-off between adult and
#'        paediatric cases.
#' @param sex Can be "Both", "Males" or "Females".
#' @param num_years_to_estimate Number of years to model.
#' @param N_boot Number of bootstrapped calculations to perform.
#' @param Max_Yearly_Incidence A number larger than the expected yearly incidence
#'        to allow for variation in incidence between years.
#' @return Predicted number of prevalent cases for each year, the age distribution of the
#'        prevalent cases, an indication of sampling variation and raw incidence data to
#'        allow for crosschecking with previous calculations.
#' @examples
#' by_year_total <- prevalence_current(load_data(registry_data), registry_years, registry_start_year,
#'                            registry_end_year, daily_survival_males = daily_survival_males,
#'                            daily_survival_females = daily_survival_females, cure = 10,
#'                            num_years_to_estimate = 10)
prevalence_current <- function(data, registry_years, registry_start_year, registry_end_year, num_years_to_estimate,
                               daily_survival_males, daily_survival_females, cure,
                               N_boot = 1000, Max_Yearly_Incidence = 500){

    if(mean(data$sex) == 0 | mean(data$sex) == 1) type = "single"
    if(mean(data$sex) != 0 | mean(data$sex) != 1) type = "both"

    data_r <- data[data$date_initial >= registry_years[registry_start_year], ]
    est_years <- registry_end_year - registry_start_year + 1

    cure_days<- 365*cure

    if(cure_days > 0){
        wb_boot <- registry_survival_bootstrapped_current(data = data[data$date_initial >= registry_years[registry_start_year], ], N_boot)
    } else{
        wb <- survreg(Surv(survival_time, indicator) ~ age_initial + sex, data=data)
        wb_boot <- t(vapply(1:N_boot, function(x) c(wb$coe, wb$scale), FUN.VALUE = numeric(4)))
    }
    wb_boot <- wb_boot[sample(nrow(wb_boot)), ]

    if(type != "both"){

        fix_rate <- incidence_current(data, registry_years, registry_start_year, registry_end_year)
        if(mean(data$sex) == 0){
            prior_age_d <- data_r$age_initial[data_r$sex == 0]
        }else{
            prior_age_d <- data_r$age_initial[data_r$sex == 1]
        }
        post_age_dist <- array(NA, dim = c(num_years_to_estimate, N_boot, Max_Yearly_Incidence))
        by_year_samples <- matrix(NA, nrow=num_years_to_estimate, ncol=N_boot)
        fix_rate_rev <- rev(fix_rate)
        mean_rate <- mean(fix_rate)

        for (j in 1:num_years_to_estimate){
            year_no <- j - 1
            boot_out <- rep(NA, N_boot)
            for (i in 1:N_boot){
                rate <- max(0, rnorm(1, mean_rate, sqrt(mean_rate)/est_years))
                if(j <= est_years){
                    rate <- fix_rate_rev[j]
                }

                no_diag <- rpois(1, rate)
                boot_age_dist <- sample(prior_age_d, no_diag, replace=T)

                diag_time <- year_no * 365 + runif(no_diag, 0, 365)

                if(mean(data$sex) == 0){
                    d_or_a <- rbinom(no_diag, 1, 1 - prob_alive_current(diag_time, boot_age_dist, sex = 0,
                                                                cure_days, boot = wb_boot[i,], daily_survival = daily_survival_males))
                }else{
                    d_or_a <- rbinom(no_diag, 1, 1 - prob_alive_current(diag_time, boot_age_dist, sex = 1,
                                                                        cure_days, boot = wb_boot[i,], daily_survival = daily_survival_females))
                }

                K_ages <- length(diag_time[d_or_a == 0])
                if(K_ages > 0) post_age_dist[j , i, 1:K_ages] <-
                    diag_time[d_or_a == 0]/365 + boot_age_dist[d_or_a == 0]
                boot_out[i] <- no_diag - sum(d_or_a)
            }

            by_year_samples[j, ] <- boot_out

        }

    }else{

        prior_age_d_male <- data_r$age_initial[data_r$sex == 0]
        prior_age_d_female <- data_r$age_initial[data_r$sex == 1]

        post_age_dist_male <- array(NA, dim = c(num_years_to_estimate, N_boot, Max_Yearly_Incidence))
        post_age_dist_female <- array(NA, dim = c(num_years_to_estimate, N_boot, Max_Yearly_Incidence))

        by_year_male_samples <- matrix(NA, nrow=num_years_to_estimate, ncol=N_boot)
        by_year_female_samples <- matrix(NA, nrow=num_years_to_estimate, ncol=N_boot)

        fix_m_rate <- rev(incidence_current(data = data[data$sex == 0, ], registry_years, registry_start_year, registry_end_year))
        fix_f_rate <- rev(incidence_current(data = data[data$sex == 1, ], registry_years, registry_start_year, registry_end_year))

        mean_rate_male <- mean(fix_m_rate)
        mean_rate_female <- mean(fix_f_rate)

        for (j in 1:num_years_to_estimate){
            year_no <- j - 1
            boot_out_male <- rep(NA, N_boot)
            boot_out_female <- rep(NA, N_boot)
            for (i in 1:N_boot){
                male_rate <- max(0, rnorm(1, mean_rate_male, sqrt(mean_rate_male)/est_years))
                female_rate <- max(0, rnorm(1, mean_rate_female, sqrt(mean_rate_female)/est_years))
                if(j <= (registry_end_year - registry_start_year + 1)){
                    male_rate <- fix_m_rate[j]
                    female_rate <- fix_f_rate[j]
                }
                no_diag_male <- rpois(1, male_rate)
                no_diag_female <- rpois(1, female_rate)
                boot_age_dist_male <- sample(prior_age_d_male, no_diag_male, replace=T)
                boot_age_dist_female <- sample(prior_age_d_female, no_diag_female, replace=T)

                diag_time_male <- year_no * 365 + runif(no_diag_male, 0, 365)
                diag_time_female <- year_no * 365 + runif(no_diag_female, 0, 365)
                d_or_a_male <- rbinom(no_diag_male, 1,
                                      1 - prob_alive_current(diag_time_male, boot_age_dist_male, sex = 0,
                                                             cure_days, boot = wb_boot[i,], daily_survival = daily_survival_males))
                d_or_a_female <- rbinom(no_diag_female, 1,
                                        1 - prob_alive_current(diag_time_female, boot_age_dist_female, sex = 1,
                                                               cure_days, boot = wb_boot[i,], daily_survival = daily_survival_females))
                K_ages_m <- length(diag_time_male[d_or_a_male == 0])
                K_ages_f <- length(diag_time_female[d_or_a_female == 0])
                if(K_ages_m > 0) post_age_dist_male[j , i, 1:K_ages_m] <-
                    diag_time_male[d_or_a_male == 0]/365 + boot_age_dist_male[d_or_a_male == 0]
                if(K_ages_f > 0) post_age_dist_female[j , i, 1:K_ages_f] <-
                    diag_time_female[d_or_a_female == 0]/365 + boot_age_dist_female[d_or_a_female == 0]
                boot_out_male[i] <- no_diag_male - sum(d_or_a_male)
                boot_out_female[i] <- no_diag_female - sum(d_or_a_female)
            }
            by_year_male_samples[j, ] <- boot_out_male
            by_year_female_samples[j, ] <- boot_out_female

        }

        by_year_samples <- by_year_male_samples + by_year_female_samples
        post_age_dist <- abind(post_age_dist_male, post_age_dist_female, along=2)
        fix_rate <- rev(fix_m_rate + fix_f_rate)

    }

    by_year <- apply(by_year_samples, 1, mean)
    return(list(by_year, post_age_dist, by_year_samples, fix_rate))

}

=======
>>>>>>> 8ee5417fd88bc48262d9b98deff8da3c8bddf276
#' Calculate predicted prevalence for a given number of years.
#'
#' @param object Object returned from prevalence\(\).
#' @param num_years_to_estimate Integer representing number of years prevalence is to be calculated for.
#' @param population_size Integer corresponding to the size of the population.
#' @param level Double representing the desired confidence interval width.
#' @param precision Integer representing the number of decimal places required.
#' @return An estimate of prevalence, in total and /100,000 with confidence intervals.
#' @examples
#' n_year_estimates(prevalence_total, num_years_to_estimate = 3, population_size = 1700000)
n_year_estimates <- function(object, num_years_to_estimate,
                             population_size,
                             level=0.95, precision=2){

    if (num_years_to_estimate > object$nyears)
        stop("Error: Can't calculate prevalence for more years than present in the prevalence object.")

    num_reg_years <- object$nregyears

    z_level <- qnorm((1+level)/2)

    the_samples <- object$samples[(num_reg_years + 1):num_years_to_estimate, , drop=F]
    by_sample_estimate <- colSums(the_samples)

    the_estimate <- sum(object$simulated_cases[1:num_years_to_estimate])
    raw_proportion <- the_estimate / population_size
    the_proportion <- 100000 * raw_proportion

    if (num_years_to_estimate <= num_reg_years) {
        se <- (raw_proportion * (1 - raw_proportion)) / population_size
    } else {
        the_estimate_n <- sum(object$simulated_cases[1:num_reg_years])
        raw_proportion_n <- the_estimate_n / population_size
        std_err_1 <- sqrt((raw_proportion_n * (1 - raw_proportion_n)) / population_size)
        std_err_2 <- sd(by_sample_estimate)/population_size
        se <- std_err_1^1 + std_err_2^2
    }

    CI <- z_level * sqrt(se) * 100000
    object <- list(absolute.prevalence=the_estimate, per100K=the_proportion,
                   per100K.lower=the_proportion - CI,
                   per100K.upper=the_proportion + CI)
    lapply(object, round, precision)
}

<<<<<<< HEAD
#' Calculate predicted prevalence for a given number of years.
#'
#' @param num_years_to_estimate Number of years prevalence is to be calculated for.
#' @param registry_start_year Ordinal defining the first year of the registry data to be used.
#' @param registry_end_year Ordinal defining the last year of the registry data to be used.
#' @param the_samples Bootstrapped samples used to gauge the sampling variation in the estimates.
#' @param by_year Predicted prevalence by year of the registry.
#' @param population_size A number corresponding to the size of the population.
#' @return An estimate of prevalence, in total and /100,000 with confidence intervals.
#' @examples
#' n_year_estimates_current(num_years_to_estimate = 3, registry_start_year = year1, registry_end_year = lastyear,
#'                  the_samples = by_year_male_samples,
#'                  by_year = by_year_male, population_size = 1700000)
n_year_estimates_current <- function(num_years_to_estimate, registry_start_year, registry_end_year,
                                     the_samples, by_year, population_size){
    if (num_years_to_estimate > length(by_year)) stop("error: too many years for the data.")

    the_samples <- the_samples[(registry_end_year - registry_start_year + 2):num_years_to_estimate, , drop=F]
    by_sample_estimate <- apply(the_samples, 2, sum)

    the_estimate <- sum(by_year[1:num_years_to_estimate])

    raw_proportion <- the_estimate / population_size
    the_proportion <- 100000 * raw_proportion

    if (num_years_to_estimate <= (registry_end_year - registry_start_year + 1)){
        CI <- (1.96 * sqrt((raw_proportion * (1 - raw_proportion))/population_size)) * 100000
    }else {
        the_estimate_n <- sum(by_year[1:(registry_end_year - registry_start_year + 1)])
        raw_proportion_n <- the_estimate_n / population_size
        std_err_1 <- sqrt((raw_proportion_n * (1 - raw_proportion_n))/population_size)
        std_err_2 <- sd(by_sample_estimate)/population_size

        CI <<- 1.96 * sqrt(std_err_1^2 + std_err_2^2) * 100000
    }

    raw <- paste("raw: ", round(the_estimate, 2), sep="")
    prop <- paste("/100,000 cases: ", round(the_proportion, 2),
                  " (", round(the_proportion - CI, 2),
                  "-", round(the_proportion + CI, 2), ")", sep="")

    return(list(raw, prop))
}

=======
>>>>>>> 8ee5417fd88bc48262d9b98deff8da3c8bddf276
#' Output extrapolated number of prevalent cases for specified age bands.
#'
#' @param object Object returned by prevalence\(\) from which to extrapolate.
#' @param age_intervals Vector of integers to delineate age bands.
#' @return Vector of predicted number of prevalent cases for specified age bands.
#' @examples
#' prevalence_by_age(dist = post_age_dist_male, registry_end_year = 4,
#'                  num_years_to_estimate = num_years_to_estimate)
prevalence_by_age <- function(object, age_intervals=seq(10, 80, by=10)) {

    if (object$nregyears >= object$nyears)
        stop("Error: No simulated prevalent years as registry data was available.")

    if (! all(age_intervals >= 0))
        stop("Must have positive ages")

    the_dist <- object$post[, , (object$nregyears + 1):object$nyears]
    the_dist <- the_dist[!is.na(the_dist)]

    # Add lower and upper bounds for range
    ages <- c(0, age_intervals, max(the_dist))

    sapply(seq(length(ages)-1),
           function(x) sum(the_dist >= ages[x] & the_dist < ages[x+1]) / length(the_dist))
<<<<<<< HEAD
}

#' Output extrapolated number of prevalent cases per 10-year age group.
#'
#' @param dist The age distribution of prevalent cases following simulation.
#' @param registry_end_year The last complete year of registry data.
#' @param num_years_to_estimate The year to make predictions until.
#' @return Predicted number of prevalent cases per 10-year age group.
#' @examples
#' result <- prevalence_by_age_current(dist = post_age_dist_male, registry_end_year = 4,
#'                  num_years_to_estimate = num_years_to_estimate)
prevalence_by_age_current <- function(dist, registry_end_year, num_years_to_estimate){

    the_dist <- dist[registry_end_year:num_years_to_estimate, , ]
    the_dist <- unlist(the_dist)
    the_dist <- the_dist[!is.na(the_dist)]

    aL <- length(the_dist)

    a_0_9 <- length(the_dist[the_dist > 0 & the_dist < 10])/aL
    a_10_19 <- length(the_dist[the_dist >= 10 & the_dist < 20])/aL
    a_20_29 <- length(the_dist[the_dist >= 20 & the_dist < 30])/aL
    a_30_39 <- length(the_dist[the_dist >= 30 & the_dist < 40])/aL
    a_40_49 <- length(the_dist[the_dist >= 40 & the_dist < 50])/aL
    a_50_59 <- length(the_dist[the_dist >= 50 & the_dist < 60])/aL
    a_60_69 <- length(the_dist[the_dist >= 60 & the_dist < 70])/aL
    a_70_79 <- length(the_dist[the_dist >= 70 & the_dist < 80])/aL
    a_80_plus <- length(the_dist[the_dist >= 80])/aL

    return(c(a_0_9,  a_10_19, a_20_29, a_30_39, a_40_49, a_50_59,
             a_60_69, a_70_79, a_80_plus))
=======
>>>>>>> 8ee5417fd88bc48262d9b98deff8da3c8bddf276
}