#' General population survival data.
#'
#' A dataset containing basic mortality rates of males and females of different ages from
#' the UK population, obtained from:
#' \url{http://www.ons.gov.uk/ons/taxonomy/index.html?nscl=Life+Tables#tab-data-tables}.
#' Adapted from public sector information licensed under the Open Government Licence v3.0.
#' Data were relabelled according to the mean year of the three-year birth window.
#' The user is advised to select "population_data" or "population_data_mx" according to their needs.
#'
#' @format A data frame with 6666 rows and 4 variables:
#' \describe{
#'  \item{calendar_year}{year}
#'  \item{sex}{sex, "Males" or "Females"}
#'  \item{age}{age, in years}
#'  \item{rate}{death rate, by year}
#' }
"population_data"

#' General population survival data.
#'
#' A dataset containing central rates of mortality of males and females of different ages from
#' the UK population, obtained from:
#' \url{http://www.ons.gov.uk/ons/taxonomy/index.html?nscl=Life+Tables#tab-data-tables}.
#' Adapted from public sector information licensed under the Open Government Licence v3.0.
#' Data were relabelled according to the mean year of the three-year birth window.
#' The user is advised to select "population_data" or "population_data_mx" according to their needs.
#'
#' @format A data frame with 6666 rows and 4 variables:
#' \describe{
#'  \item{calendar_year}{year}
#'  \item{sex}{sex, "Males" or "Females"}
#'  \item{age}{age, in years}
#'  \item{rate}{death rate, by year}
#' }
"population_data_mx"

#' Population survival rate.
#'
#' @param data A dataset of population survival data by year.
#' @param sex Can be "Males" or "Females".
#' @return An estimate of the survival rate by day for ages <=100 years.
#' @examples
#' daily_survival_males <- daily_survival_rate(population_data_mx, sex = "Males")
#' daily_survival_females <- daily_survival_rate(population_data_mx, sex = "Females")
population_survival_rate_dev <- function(form, data, max_age=100){
  # Could probably improve on this extraction of response and variable
  age_var <- as.character(form[[3]])
  rate_var <- as.character(form[[2]])

  rate <- vapply(seq(0, max_age-1),
                 function(x) mean(data[data[,age_var]==x, rate_var]),
                 numeric(1))

  a_rate <- c(2 * rate[1] - rate[2], rate, 2 * rate[max_age] - rate[max_age-1])
  base <- 183 + 365 * (1:max_age) # Where does 183/182 come from?
  base <- c(-182, 183, base)
  daily_rate <- approx(base, a_rate, 1:(max_age * 365))
  daily_rate <- daily_rate$y / 365
  cumprod(1 - daily_rate)
}

daily_survival_rate_current <- function(data, sex){

  if(sex != "Males" & sex != "Females") stop("error: incorrect sex.")
  data <- as.data.frame(data)
  if(sex == "Males") data = filter(data, sex == 0)
  if(sex == "Females") data = filter(data, sex == 1)
  data <- data %>%
    select(age, rate)

  rate <- rep(NA, 100)
  for (i in 0:99){
    rate[i + 1] <- mean(data$rate[data$age == i])
  }
  a_rate <- c(2 * rate[1] - rate[2], rate, 2 * rate[100] - rate[99])
  daily_rate <- rep(0, 365 * 100)
  base <- 183 + 365 * (1:100)
  base <- c(-182, 183, base)
  daily_rate <- approx(base, a_rate, 1:(100 * 365))
  daily_rate <- daily_rate$y
  daily_rate <- daily_rate/365
  return(daily_rate)

}

#' Calculate bootstrap survival coefficients as a way to estimate uncertainty
#' of the survival model.
#' @param data Dataset of patient cases generated by load_data(), restricted to the first complete year
#'        of the registry.
#' @param N_boot Number of replicates.
#' @return The coefficients from a Weibull survival model fitted to each bootrapped sample.
#' @examples
#' registry_survival_bootstrapped(data, N_boot = 1000)
registry_survival_bootstrapped_dev <- function(form, data, N_boot = 1000){
  data_trans <- .transform_registry_data(form, data) # df -> matrix, log transform stimes
	n_obs <- nrow(data_trans)
  coefs <- t(vapply(1:N_boot,
             function(x) {
                  ith_data <- data_trans[sample(1:n_obs, n_obs, replace=T), ]
                  wbb <- .fit_weibull(ith_data)
             },
             numeric(4)))
  # Need to transform scale back from log scale
  coefs[, ncol(coefs)] <- exp(coefs[, ncol(coefs)])
  coefs
}

.fit_weibull <- function(data) {
  model <- survreg.fit(data[, 3:ncol(data)],
                       data[, 1:2],
                       NULL, # weights
                       numeric(nrow(data)), # offset
                       NULL, # init
                       survreg.control(), # controlvars
                       survreg.distributions[['extreme']], # dist
                       0, # scale
                       1, # nstrat
                       0, # strata
                       NULL # parms
                       )
  coef(model)
}

.transform_registry_data <- function(form, data) {
  # Transforms the registry data into the format specified by survreg.fit,
  # i.e. as a matrix of values with the survival times log transformed.
  complete <- data[complete.cases(data), ]
  X = model.matrix(form, complete)
  survobj <- with(complete, eval(form[[2]]))
	Y <- cbind(log(survobj[, 1]), survobj[, 2])
	data_trans <- cbind(Y, X)
}


registry_survival_bootstrapped_current <- function(data, N_boot = 1000){

  boot <- matrix(0, nrow=N_boot, ncol=4)
  for (i in 1:N_boot){
    ith_sample <- sample(1:(dim(data)[1]), dim(data)[1], replace=T)
    ith_data <- data[ith_sample, ]
    wbb <- survreg(Surv(survival_time, indicator) ~ age_initial + sex, data=ith_data)
    boot[i, ] <- c(wbb$coe, wbb$scale)
  }

  return(boot)

}

#' Survival function for males or females, modelled on patient data until cure_time, then
#' population data for the remaining time.
#'
#' @param time Time in days.
#' @param age Age of the patient in years.
#' @param sex Sex of the patient (0 for males, 1 for females).
#' @param cure_time A number representing time in days corresponding to the cure model assumption for the calculation.
#' @param boot Selected bootstrapped dataset.
#' @param daily_survival Population survival function in days.
#' @return A survival curve on which to base prevalence predictions.
prob_death <- function(time, age, sex, cure_time, boot, daily_survival){
  ifelse(age*365 + time > 36500,
         0,
         ifelse(time < cure_time,
                1 - pweibull(time, scale=exp(boot[1] + age*boot[2] + sex*boot[3]),
                             shape=1/boot[4]),
                (1 - pweibull(cure_time, scale=exp(boot[1] + age*boot[2] + sex*boot[3]),
                              shape=1/boot[4])) * daily_survival[age*365 + time]/daily_survival[age*365 + cure_time]))
}